[package]
name = "hardshare"
version = "0.11.0-devel"
authors = ["Scott C. Livingston <scott@rerobots.net>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
home = "0.5.3"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
actix = "0.10"
actix-codec = "0.3"
actix-web = "3"
actix-web-actors = "3"
awc = { version = "2", features = ["openssl"] }
bytes = "0.5"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
jwt = { version = "0.11", features = ["openssl"] }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = [ "color" ]

[dev-dependencies]
assert_cmd = "1.0"
tempfile = "3.1"
mockito = "0.30.0"
