# Base image with packages required for PlatformIO (https://platformio.org/)
#
#     docker build -t rerobots/hs-generic-platformio:latest -f Dockerfile-platformio .
#
#
# SCL <scott@rerobots.net>
# Copyright (C) 2020 rerobots, Inc.

FROM rerobots/hs-generic:latest

# Install PlatformIO
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-venv

RUN wget https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -O get-platformio.py \
    && export LC_ALL=C.UTF-8 LANG=C.UTF-8 \
    && python3 get-platformio.py

RUN echo 'export LC_ALL=C.UTF-8 LANG=C.UTF-8' >> /root/.bashrc \
    && echo 'source /root/.platformio/penv/bin/activate' >> /root/.bashrc

# Build and install platformio-proxy
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    curl \
    libclang-dev \
    libudev-dev \
    pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
    && sh rustup.sh -y

RUN git clone --depth=1 https://github.com/rerobots/hardshare.git
RUN . $HOME/.cargo/env \
    && cd hardshare \
    && export CMAKE_POLICY_VERSION_MINIMUM=3.5 \
    && cargo build --bin platformio-proxy --release --locked \
    && mv target/release/platformio-proxy /usr/local/bin/ \
    && cargo clean \
    && cd .. && rm -rf hardshare

CMD ["/sbin/rerobots-hs-init.sh"]
