# Base image with packages required for PlatformIO (https://platformio.org/)
#
#     docker build -t rerobots/hs-generic-platformio:latest -f devices/generic/Dockerfile-platformio .
#
#
# SCL <scott@rerobots.net>
# Copyright (C) 2020 rerobots, Inc.

FROM rerobots/hs-generic:latest

# Install PlatformIO
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-venv

RUN wget https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -O get-platformio.py \
    && export LC_ALL=C.UTF-8 LANG=C.UTF-8 \
    && python3 get-platformio.py

RUN echo 'export LC_ALL=C.UTF-8 LANG=C.UTF-8' >> /root/.bashrc \
    && echo 'source /root/.platformio/penv/bin/activate' >> /root/.bashrc

# Build and install platformio-proxy
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    curl \
    libclang-dev \
    libudev-dev \
    pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
    && sh rustup.sh -y

RUN test `uname -m` = x86_64 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libjpeg-dev \
    nasm

RUN mkdir -p hardshare
COPY Cargo.toml Cargo.lock /root/hardshare/
COPY src /root/hardshare/src/
COPY integrations/platformio /root/hardshare/integrations/platformio/
RUN . $HOME/.cargo/env \
    && cd /root/hardshare \
    && export CMAKE_POLICY_VERSION_MINIMUM=3.5 \
    && cargo build --bin platformio-proxy --release --locked \
    && mv target/release/platformio-proxy /usr/local/bin/

# Requires instances with environment variable
# PLATFORMIO_EXTRA_SCRIPTS=/usr/local/lib/rerobots/pio.py
# cf. https://docs.platformio.org/en/latest/envvars.html
RUN cd /root/hardshare \
    && mkdir -p /usr/local/lib/rerobots \
    && cp integrations/platformio/rerobots_pio.py /usr/local/lib/rerobots/pio.py

RUN . $HOME/.cargo/env \
    && cd /root/hardshare \
    && cargo clean \
    && cd .. && rm -rf hardshare

CMD ["/sbin/rerobots-hs-init.sh"]
