# Base image with packages required for RAK4631 development
#
#     docker build -t rerobots/hs-rakwireless-rak4631:latest -f Dockerfile-rak4631 .
#
#
# SCL <scott@rerobots.net>
# Copyright (C) 2023 rerobots, Inc.

FROM rerobots/hs-generic-platformio:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip

COPY platformio-rak4631.ini /root/platformio.ini

# run command will fail, but this will fetch and install dependencies
RUN cd /root/ \
    && mkdir src \
    && echo "#include <Arduino.h>" > src/main.cpp \
    && echo "#include <SPI.h>" >> src/main.cpp \
    && echo "void setup() {}" >> src/main.cpp \
    && echo "void loop() {}" >> src/main.cpp \
    && bash -c "source $HOME/.platformio/penv/bin/activate \
    && platformio run \
    || true"

RUN cd /root/ \
    && wget https://github.com/RAKWireless/WisBlock/raw/8d851fba7693f9339db0f857a92cd816163c5f7a/PlatformIO/RAK_PATCH.zip -O RAK_PATCH.zip \
    && mkdir .platformio/RAK_PATCH && cd .platformio/RAK_PATCH && unzip ../../RAK_PATCH.zip \
    && bash -c "source $HOME/.platformio/penv/bin/activate \
    && python ./rak_patch.py"
# sha256sum d18cec33bc3fa297583fd3d9f6852c10c1b6cea4a361b9a6ea567f7cfcdbe9a3  RAK_PATCH.zip

# run command will fail, but this will fetch and install remaining dependencies
RUN cd /root/ \
    && bash -c "source $HOME/.platformio/penv/bin/activate \
    && platformio run \
    || true"

RUN cd /root/.platformio/RAK_PATCH \
    && bash -c "source $HOME/.platformio/penv/bin/activate \
    && python ./rak_patch.py"

# The final run command must succeed
RUN cd /root/ \
    && bash -c "source $HOME/.platformio/penv/bin/activate \
    && platformio run"

# Clean up
RUN cd /root/ \
    && rm -rf src platformio.ini

CMD ["/sbin/rerobots-hs-init.sh"]
