# docker build -t rerobots/hs-sim-avr:latest -f Dockerfile-avr .

FROM debian:stable

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install \
       openssh-server \
       openvpn \
       avahi-daemon \
       nano \
       git \
       python3 \
       python3-aiohttp \
    && mkdir -p /var/run/sshd

COPY --chmod=0775 init.sh /sbin/rerobots-hs-init.sh

WORKDIR /root

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
    build-essential \
    cmake \
    pkgconf \
    curl \
    gcc-avr \
    avr-libc \
    libelf-dev \
    libssl-dev \
    avrdude

RUN curl -L -o lws.tgz https://github.com/warmcat/libwebsockets/archive/refs/tags/v4.3.3.tar.gz \
    && tar -xzf lws.tgz
RUN cd libwebsockets-4.3.3 \
    && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE .. \
    && make && make install

RUN git clone --depth=10 https://github.com/buserror/simavr.git \
    && cd simavr && git checkout a6fc4cc754ebf4ffb1e615ba7c2ab8a6d6f8b967

RUN cd simavr \
    && make build-simavr \
    && make install-simavr

RUN git clone --depth=10 https://github.com/rerobots/simboard.git
RUN cd simboard/wrapper-simavr \
    && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE .. \
    && make

CMD ["/sbin/rerobots-hs-init.sh"]
