---
# configuration for GitHub Actions
name: hardshare client
on:
    push:
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Prepare to build
              run: |
                mkdir keys
                touch keys/public.pem
            - name: Lint
              run: |
                cargo +nightly fmt --check
                cargo check
                cargo clippy --tests -- -D clippy::all
            - name: Run tests
              run: |
                cargo test
