---
# configuration for GitHub Actions
name: hardshare client
on:
    push:
    pull_request:
jobs:
    build-and-test:
        name: Build and test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [
                    ubuntu-22.04,
                    macos-latest,
                    windows-latest,
                    ]
        steps:
            - uses: actions/checkout@v4
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Install sys packages
              if: matrix.os == 'ubuntu-22.04'
              run: |
                sudo apt update
                sudo apt install \
                    libudev \
            - name: Prepare to build
              run: |
                mkdir keys
                touch keys/public.pem
            - name: Lint
              if: runner.os != 'Windows'
              run: |
                cargo fmt --check
                cargo check
                cargo clippy --tests -- -D clippy::all
            - name: Run tests
              run: |
                cargo test
