---
# configuration for GitHub Actions
name: hardshare client
on:
    push:
    pull_request:
jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: |
                rustup toolchain install nightly --profile minimal
                rustup component add --toolchain nightly rustfmt
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Prepare to build
              run: |
                mkdir keys
                touch keys/public.pem
            - name: Lint
              run: |
                cargo +nightly fmt --check
                cargo check
                cargo clippy --tests -- -D clippy::all
            - name: Run tests
              run: |
                cargo test
